[package]
name = "hello-rust"
version = "0.1.0"
authors = ["hanhyeonkyu <busgod1212@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"